【WIP】Feature/display history uniqueid
ri-i-i-sa/member-management-system-project pull request #21
Opened 2023-06-27 18:16 UTC by ri-i-i-sa

#8

2023-06-27 18:29 UTC, ri-i-i-sa commented
@tomohitokanno 
issueにて進捗共有をした通り、データ全件取得した後にフィルタリングして結果を表示するについては実装しています。
現状、selectする前にidで検索条件を絞るの実装を試みています。

【参考URL】
https://qiita.com/roana0229/items/fea931fcabc57f193620#%E3%82%AF%E3%82%A8%E3%83%AA%E7%B5%90%E6%9E%9C-json-array

idと比較する変数、membersIdの中身がmembersId: 2のような形式であるため、下記のような手法で「2」と比較したいのですが、今のところ上手く機能していません。

`let return_data = SpreadSheetsSQL.open(id, name).select(['membersId','reserveAt','arrivalAt','arrivalFlag','paymentAmount']).filter('item => item.membersId === id').result();`

membersIdのみ一回変数に入れて別の扱いにする等で、上手く比較出来るかどうか試してみます。
（もしこうすればいいかもなどがあればご助言いただけましたら幸いです。）
取り急ぎの進捗共有となりますが、よろしくお願いします。

2023-06-27 21:46 UTC, tomohitokanno commented
@ri-i-i-sa 
まず、このSpreadSheetSQLを使用する場合のfilterは今まで配列操作で使用したfilterとは全く別物です。
SpreadSheetSQLにおけるfilterはSQL文で言うところのwhere句の役割をします。

論理名：生物テーブル 物理名：creature_table
|  id  |  name  | legs  | 
| ---- | ---- | ---- |
|  1  |  human  | 2 |
|  2  |  cat  | 4 |
|  3  |  dog  | 4 |
|  4  |  spider  | 8 |

のようなテーブルがあり、人間の足の本数を取得したい場合、SQL文では以下のように書きます。
`SELECT legs FROM creature_table WHERE name = "human";`
結果は
`2`
です。

このWHERE句を今回のSpreadSheetSQLにおけるfilterに当てはめると
`.filter('name = human')`
になります。


> idと比較する変数、membersIdの中身がmembersId: 2のような形式であるため

どのように2の変数が渡されるかは不明ですが、自分が即席で書くなら以下のような感じになるかと思います。
もしこれで動いても、理解せずに次（会員一覧の検索、来店状態のアップデート）に進むと確実にまた詰まるので、このタイミングで完全に理解してから進んでほしいです。
```
let id = 2
let return_data = SpreadSheetsSQL.open(id, name).select(['membersId','reserveAt','arrivalAt','arrivalFlag','paymentAmount']).filter('membersId = ' + id).result();
```

2023-06-28 12:14 UTC, ri-i-i-sa commented
@tomohitokanno 
具体例ありがとうございます。
実装自体は上手く出来たのですが、なぜこの記述で問題なかったのかが、いまいち理解しきれず。。

>人間の足の本数を取得したい場合、SQL文では以下のように書きます。 `SELECT legs FROM creature_table WHERE name = "human";` 結果は `2` です。
> このWHERE句を今回のSpreadSheetSQLにおけるfilterに当てはめると `.filter('name = human')` になります。

ここまでは理解出来ています。

> > idと比較する変数、membersIdの中身がmembersId: 2のような形式であるため
> どのように2の変数が渡されるかは不明ですが、自分が即席で書くなら以下のような感じになるかと思います。 もしこれで動いても、理解せずに次（会員一覧の検索、来店状態のアップデート）に進むと確実にまた詰まるので、このタイミングで完全に理解してから進んでほしいです。
> let id = 2
> let return_data = SpreadSheetsSQL.open(id, name).select(['membersId','reserveAt','arrivalAt','arrivalFlag','paymentAmount']).filter('membersId = ' + id).result();
> ```

このあたりの理解が難しく、今回の例で言うとhuman,cat,dog,spiderが特定の変数（仮にID）と合致するかどうか知りたい場合になぜ下記のように記述が必要なのかの理論がわかっていません。。このあたりはSQL特有のルールのようなものなのでしょうか？？

`.filter('name = ' + id)`

2023-06-29 10:17 UTC, ri-i-i-sa commented
@tomohitokanno 
下記の実装が完了しています。
・合計金額表示
・ID表示
・データなしの場合のテキスト表示

レビューの前にまだ少しコードの見直しをしたいのですが、取り急ぎデータなしの場合のテキスト表示の見た目について問題がないかどうかご確認いただくことは可能でしょうか？？
ID=3の会員データを削除しておりますので、そちらでご確認いただけますと幸いです。

2023-06-30 09:18 UTC, ri-i-i-sa commented
@tomohitokanno 
リファクタリング作業を行い、レビューが可能な状態になっています。
お手数ですが、ご確認のほどよろしくお願いいたします。

2023-06-30 10:53 UTC, tomohitokanno requested changes
修正おなしゃす

2023-06-30 10:53 UTC, tomohitokanno commented on history.html
> +        <span class="totaltext">合計金額 <span class="totalprice">【¥99,999】</span>
APIの処理を待ってる間ずっと【¥99,999】が表示されてしまうので、ここにダミーの値は要らないかなと思いました。

2023-06-30 10:53 UTC, tomohitokanno commented on history.html
>        <table class="member-view flex">
`</P>`タグは改行しなくても良いと思います。
また、text-for-hideは命名が良くないです。
**履歴はありません** をただ表せばよいです。自分ならno-history-messageにします。
text-for-hideだと隠れてる文字ということはつまり？と思ってしまいます。
隠しているそのものが何なのかを表現すれば良いのです。

2023-06-30 10:53 UTC, tomohitokanno commented on history.html
> +        <span class="totaltext">合計金額 <span class="totalprice">【¥99,999】</span>
このclass名だけケバブで定義されていないので一貫性がないです。

2023-06-30 10:53 UTC, tomohitokanno commented on assets/js/history-script.js
> +  $(".member-view").html($tableRows);
` $(".text-for-hide") `
に対する表示の切り替えが処理の中に3行あるのは違和感があります。
データがなければshow
データだあればhideの2パターンしかないのになぜ1つの処理にhideが2つあるのでしょうか

2023-06-30 10:53 UTC, tomohitokanno commented on assets/js/history-script.js
> +        $totalAmount += json[i].paymentAmount;
DOMを作成している行のど真ん中に金額加算の処理は置かずに、別のところに書いてほしいです。

2023-06-30 10:53 UTC, tomohitokanno commented on assets/js/history-script.js
> +      $(".totaltext").html("合計金額: ").append($totalAmountDOM);
合計金額は置換しないといけない要素なのでしょうか？

2023-06-30 10:53 UTC, tomohitokanno commented on assets/js/history-script.js
> +        let paymentTotal = formatAmount(json[i].paymentAmount);
いまさらですが、変数を再利用しないのならば
一個一個を変数にせずに直接埋め込めばいいんじゃないかなと思います。script.jsの方も同様で

2023-06-30 10:53 UTC, tomohitokanno commented on assets/js/history-script.js
> +    memberId: urlParams.get('memberId'),
memberNameが何故か特別扱いされているので、このparamsに入れて管理すればいいのでは？と思いました。

2023-06-30 10:53 UTC, tomohitokanno commented on assets/js/script.js
> +      $lineDOM.append($('<td><div class="flex"><div class="button-date"><a href="#" class="text-medium">来店登録</a></div><div class="button-history"><a href="./history.html" class="text-medium" id="' +
1行を長くしすぎるとこのように末尾にコメント書いたのを間違ってcommitしてしまいます。
改行をしてください。

2023-06-30 10:53 UTC, tomohitokanno commented on assets/js/script.js
> +      url.search = new URLSearchParams(combinedParams).toString();
要素が1つしかない配列を3つ作ってそれをコンバインするのであれば、
パラメーターで使用する値はparamsに追加して、不要なidParamsとnameParamsを作らなければいいと思います。
コンバインという余計な処理・変数を増やさなくて済みます。

2023-06-30 10:53 UTC, tomohitokanno commented on assets/js/script.js
> +      url = new URL("./history.html", window.location.href);
letをつけてあげてください。

2023-06-30 11:20 UTC, ri-i-i-sa commented on assets/js/history-script.js
> +  $(".member-view").html($tableRows);
@tomohitokanno 
ここでデフォルトをhide状態にしないとAPI側で件数取得するまでの数秒「履歴がありません」の表示が出てしまうため、記述しています。

2023-06-30 11:26 UTC, ri-i-i-sa commented on assets/js/history-script.js
> +        let paymentTotal = formatAmount(json[i].paymentAmount);
@tomohitokanno 
現状大半が再利用していないのですが、一部ボタンに埋め込んでいる箇所などで利用している変数が2つほどあります。
その場合も全て直接埋め込みで問題ないでしょうか？
そこに使っている文だけ変数に入れたほうが良いですか？

2023-06-30 11:31 UTC, ri-i-i-sa commented on assets/js/history-script.js
> +    memberId: urlParams.get('memberId'),
@tomohitokanno 
元々(リファクタリング作業前）はparamsに入れていたのですが、ここに入れるとGASのURLにパラメータとして付与されてしまいます。付与されること自体は問題ないと思うのですが、現状特に不要な情報なのでparamsの変数内には格納せず、名前表示用の別の変数に入れています。

一応意図はあったのですが、どちらの形が正しいか（または別の手法があるか）ご教示いただけましたら幸いです。

2023-06-30 11:52 UTC, ri-i-i-sa commented on assets/js/script.js
> +      url = new URL("./history.html", window.location.href);
@tomohitokanno 
直したのですが、変数名が重複していて分かりづらかったためredirectURLという名前に変更しました。

2023-06-30 11:57 UTC, ri-i-i-sa commented
@tomohitokanno 
ご指摘頂いた内容につきまして、問題ないものは修正、一部確認が必要なものには返信コメントを記載しました。
度々お手数ですがご確認お願いいたします。

2023-06-30 12:01 UTC, tomohitokanno commented on assets/js/history-script.js
> +  $(".member-view").html($tableRows);
@ri-i-i-sa 
であればHTMLのメッセージを直接hidden=trueにして、
js側で0件結果が帰ってきた場合のみhidden=falseにすればよいかと思います。

2023-06-30 12:03 UTC, tomohitokanno commented on assets/js/history-script.js
> +        let paymentTotal = formatAmount(json[i].paymentAmount);
@ri-i-i-sa 
> 一部ボタンに埋め込んでいる箇所

これはどこのことを指していますか？
自分が見た限り1度も再利用していないです。

2023-06-30 12:08 UTC, ri-i-i-sa commented on assets/js/history-script.js
> +        let paymentTotal = formatAmount(json[i].paymentAmount);
@tomohitokanno 
L:40,41の箇所です。
`      $lineDOM.append($('<td><div class="flex"><div class="button-date"><a href="#" class="text-medium">来店登録</a></div><div class="button-history"><a href="./history.html" class="text-medium" id="' 
                        + membersId + '" data-name="' + membersName + '">来店履歴</a></div></div></td>'));  
`

2023-06-30 12:31 UTC, tomohitokanno commented on assets/js/history-script.js
> +    memberId: urlParams.get('memberId'),
> 名前表示用の別の変数に入れています。

使い分け注意です。これは定数です。

履歴取得のAPIのrequestパラメータにmemberNameは不要ということですね、理解しました。
であればこの定数は再利用していないのでmemberNameDOMを生成している行に直接デコードした文字を入れましょう。

2023-06-30 12:36 UTC, tomohitokanno commented on assets/js/script.js
> +      url = new URL("./history.html", window.location.href);
@ri-i-i-sa 
変数名が重複していると1回目(L:10)に宣言した変数に再代入することになります。
このように再代入を無意識下に行ってしまうと予期せぬバグが起こってしまうので注意してください。

あとこのボタンが発火した際のイベントはリダイレクトではないので命名し直してください。

2023-06-30 13:00 UTC, tomohitokanno commented on assets/js/history-script.js
> +        let paymentTotal = formatAmount(json[i].paymentAmount);
@ri-i-i-sa 
script.jsの方ですね。
じゃあこうしましょう、

（書いちゃったので載せます）

jsonをまるごと連想配列に変換するfunctionを作る
```
function jsonToDictionary(json){
  return {
    memberId: json.id,
    memberName: json.name,
    memberFurigana: json.furigana,
    memberGender: getGenderText(json.gender),
    memberTel: json.tel,
    memberBirthday: birthdayToString(json.birthday),
    memberStatus: getStatusText(json.status)
  };
}
```

json内の会員をi件ずつループさせる処理内で呼び出す。
`      let memberInfo = jsonToDictionary(json[i]);`

DOMの生成時にこのように使う。
`      $lineDOM.append($('<td>' + memberInfo.memberId + '</td>'));`


メインのでかい処理の中でletをたくさん宣言するよりもこのようにメインの処理の外でまるごと変換し、1つの変数にメンバーの情報を集約させればコードの見通しが良くなります。

2023-06-30 13:01 UTC, tomohitokanno commented
@ri-i-i-sa 
返信コメント書ききりました、修正お願いします。

2023-06-30 13:16 UTC, ri-i-i-sa commented on assets/js/script.js
> +      url = new URL("./history.html", window.location.href);
@tomohitokanno 
すみません、「このボタンが発火した際のイベント」が何を指しているのか理解が出来ていないのですが、

      let redirectURL = new URL("./history.html", window.location.href); 
      redirectURL.search = new URLSearchParams(params).toString();

redirectURLの変数自体には次のページ（会員履歴）のURLと付与したパラメータが入ります。
意味合い自体は合っているようにも思えるのですが、「targetURL」などのほうが適切でしょうか？

2023-06-30 13:18 UTC, ri-i-i-sa commented on assets/js/history-script.js
> +  $(".member-view").html($tableRows);
@tomohitokanno 
修正してみました。意図通りの内容になっていますでしょうか？？

2023-06-30 13:20 UTC, ri-i-i-sa commented on assets/js/history-script.js
> +      $(".totaltext").html("合計金額: ").append($totalAmountDOM);
@tomohitokanno 
すみません、こちらの指摘の確認が漏れていました。
特に置換の必要はないです。
他の場所でも置換作業をしていたので、した方がよいのかな？と判断してしまいましたが、不要であればHTMLの記述を適用します。

2023-06-30 13:21 UTC, ri-i-i-sa commented
> @ri-i-i-sa 返信コメント書ききりました、修正お願いします。

@tomohitokanno 
対応完了のものを除き、4件コメントにて返信しています。
お手数ですがご確認お願いいたします。

2023-06-30 13:26 UTC, ri-i-i-sa commented on assets/js/history-script.js
> +        let paymentTotal = formatAmount(json[i].paymentAmount);
@tomohitokanno すみません、行き違いがあって、この件まだ未対応です！！！
取り急ぎ、これから確認します！

2023-06-30 13:28 UTC, tomohitokanno commented on assets/js/script.js
> +      url = new URL("./history.html", window.location.href);
@ri-i-i-sa 
> このボタンが発火した際のイベント

`$('.button-history a').on('click', function(e) {`
この話をしています。これは来店履歴ボタンが押下されたこと検知する処理で、このブロック内は押下された場合のみ実行される処理を書くわけです。

redirectという意味をググってください。来店履歴ボタンを**押下して**来店履歴にページが移る処理はリダイレクトではなく遷移です。来店履歴ボタンを**押下せず**勝手に遷移してしまうのならリダイレクトです。（誤って用語を覚えているようなのでこのタイミングで正しく理解してください。）
ですのでredirectURLという変数名は不適切です。
targetURLは適切です。

2023-06-30 13:34 UTC, tomohitokanno commented on assets/js/history-script.js
> +  $(".member-view").html($tableRows);
@ri-i-i-sa 
hiddenではなくdisplayに様変わりしていますがそういうことです。

ですが履歴0件時にテーブルヘッダーが出てしまっているので直してください。
コミット前に履歴0件と履歴0件ではない場合の検証を行うようにしてください。（これめちゃめちゃ大事です。）

2023-06-30 13:59 UTC, ri-i-i-sa commented on assets/js/history-script.js
> +        let paymentTotal = formatAmount(json[i].paymentAmount);
@tomohitokanno 
対応しました。

2023-06-30 14:08 UTC, ri-i-i-sa commented on assets/js/script.js
> +      url = new URL("./history.html", window.location.href);
@tomohitokanno 
ありがとうございます。
諸々調べ直して修正しました。

2023-06-30 14:09 UTC, ri-i-i-sa commented
@tomohitokanno 
度々申し訳ありません。
把握してる限りの修正とコメント返信が完了しています。

ご確認お願いいたします。

2023-06-30 14:31 UTC, tomohitokanno commented
@ri-i-i-sa 
追加で、jsのDOM操作周りの操作を前サンプルコードを見せた際、DOMが格納されている変数名の頭にのみ$をつけていましたが（多分伝わってない）
変数頭の$要らないかなと思ったので除去をお願いしますまるごと

2023-07-01 03:59 UTC, ri-i-i-sa commented on assets/js/history-script.js
> +  $(".member-view").html($tableRows);
@tomohitokanno 
私が実装したやり方だとCSSでdisplay:brockを指定しデフォルト表示オフにして、０件のときのみJSの操作で表示可にしていました。
そのやり方だとCSSにもコードを加えてしまっていたので、hiddenプロパティを検索してみたのですがデフォルト表示OFFの仕方がわからず上手く実装出来ていません。。。

もしhiddenプロパティを使っての実装法がわかればご教授いただきたいです。
テーブルヘッダーもデフォルトオフにする必要があるので、手法があれば同じやり方で実装します。

2023-07-01 04:14 UTC, ri-i-i-sa commented
@tomohitokanno 
追加の指摘事項対応しました。

>変数頭の$要らないかなと思ったので除去をお願いしますまるごと

意図した修正内容になっていますでしょうか？？

hiddenの正しい記述方法がわからず、返信コメントに質問事項として記載しておりますのでお手数ですがご確認お願いいたします。

2023-07-01 04:22 UTC, ri-i-i-sa commented on assets/js/history-script.js
> +      $(".totaltext").html("合計金額: ").append($totalAmountDOM);
@tomohitokanno 
このコメントいつも隠れて表示されてしまうので、返信内容確認用のリマインドです。

2023-07-01 04:31 UTC, tomohitokanno commented
@ri-i-i-sa 
HTMLに
`<p class="msg" hidden>メッセージ</p>`
と書いて、js側で
` $(".msg").show();`
するだけです。

2023-07-01 05:42 UTC, ri-i-i-sa commented
@tomohitokanno 
ありがとうございます。
修正出来ました。

ローディングのテーブルヘッダーと合計金額も非表示に修正しています。

度々お手数ですがご確認お願いいたします。

2023-07-02 05:09 UTC, tomohitokanno requested changes

2023-07-02 05:09 UTC, tomohitokanno commented on assets/js/script.js
> +let nameParams = {};
消し忘れです。

2023-07-02 05:09 UTC, tomohitokanno commented on assets/js/history-script.js
> +$totalAmount = 0;
`$totalAmount = 0;`
この宣言はこんなに上で宣言する必要がないと思います。

2023-07-02 05:09 UTC, tomohitokanno commented on assets/js/history-script.js
> +      $(".totaltext").html("合計金額: ").append($totalAmountDOM);
@ri-i-i-sa 
こういった値が可変しない要素は置換しないでください。

2023-07-02 05:09 UTC, tomohitokanno commented on assets/js/history-script.js
> +$totalAmount = 0;
@ri-i-i-sa 
これ未対応です。それと$消し忘れです

2023-07-02 05:43 UTC, ri-i-i-sa commented on assets/js/history-script.js
> +$totalAmount = 0;
@tomohitokanno 
$は消したのですが、どこに記述すれば可読性がいいかどうか、適切な箇所がわからず悩んでします。
これまで、定数や変数はまとめて配置するものだと認識してしまっておりました。。

2023-07-02 05:44 UTC, ri-i-i-sa commented
@tomohitokanno 
追加の指摘事項について確認及び修正作業が完了しております。
度々お手数ですがご確認お願いいたします。

2023-07-02 06:44 UTC, tomohitokanno approved these changes
LGTM

2023-07-02 08:11 UTC, ri-i-i-sa commented
@tomohitokanno 
LGTM後に指摘いただいた下記の内容を追加でコミットしています。

・totalAmountの変数の宣言位置を変更

度々お手数ですがご確認お願いいたします。

2023-07-02 08:42 UTC, merged