【WIP】Feature/search function
ri-i-i-sa/member-management-system-project pull request #23
Opened 2023-07-03 07:45 UTC by ri-i-i-sa

＃14

2023-07-06 12:16 UTC, tomohitokanno commented
@ri-i-i-sa
[Implement search function.](https://github.com/ri-i-i-sa/member-management-system-project/pull/23/commits/194821ceab260bfc18b41115d8e4c41b94bade09)
このコミットメッセージだと意味合いが広すぎるので、
and検索機能を追加した のような具体性のあるメッセージを心がけてみてください。

2023-07-11 15:43 UTC, ri-i-i-sa commented
@tomohitokanno 
本プルリクエスト対象Issueの実装が完了いたしました。

レイアウトの崩れが現時点で発生しており、別のタスクとして扱っても良いのかな、と考えています。
具体的には会員表示の横幅が最大文字数（現状はNo.3）に合わせて整っているため、他の会員のみの表示だとレイアウト崩れが発生してしまいます。

もし現時点での修正が必要であればお知らせください。
一旦考慮しないようであれば、お手隙の際にレビューをお願いしたく存じます。

お手数ですが、ご確認お願いいたします。

2023-07-11 16:55 UTC, tomohitokanno requested changes
@ri-i-i-sa 
レビューしました。

5件の指摘の他に、大きい範囲で以下を修正していただきたいです。


HTML、js上でidとclassの使い分けがしっかりと定義されていないと感じます。

例えばですが、現状のソースでは検索ボタンのidにはsearch-buttonと定義されていますが、使用されておらず、jQueryの操作はclass名を指定し操作されています。

idの属性、classの属性を明確に使い分けるようリファクタを行ってください。
その際に保守性、拡張性のを考慮し、リファクタの方向性を決めてください。

2023-07-11 16:55 UTC, tomohitokanno commented on assets/js/script.js
> +          case matchFalse:
matchFalseの場合処理なしであれば、条件を消してしまいましょう。

2023-07-11 16:55 UTC, tomohitokanno commented on assets/js/script.js
>  $tableRows = createHeaderDOM();
前回のレビューでの見落としですが、この変数の$は取りましょう。

2023-07-11 16:55 UTC, tomohitokanno commented on assets/js/script.js
> +  var formattedValue = value;
varでの変数宣言はなるべくやめてください。
スコープの都合でvarでなければならない場合のみに使用を限定してください。
関数：limitInputLength
関数：truncateValue
も同様です。

2023-07-11 16:55 UTC, tomohitokanno commented on assets/js/script.js
> +function limitInputLength(input) {
oninput用の関数はscript.jsファイルの下の方にまとめておいてください。

2023-07-11 16:55 UTC, tomohitokanno commented on assets/js/script.js
> +    var charCode = value.charCodeAt(i);
charCodeは記述を明示的にするために変数にされていますが、
再利用されないので変数にする必要はないかなと感じます。

2023-07-14 13:34 UTC, ri-i-i-sa commented
@tomohitokanno 
ご指摘いただいた内容を反映し、修正対応いたしました。

> idの属性、classの属性を明確に使い分けるようリファクタを行ってください。
> その際に保守性、拡張性のを考慮し、リファクタの方向性を決めてください。

上記につきましては、jsからの要素指定にはすべてidを使用するように定め、新たに追加をしております。

お手数ですが、ご確認お願いいたします。

2023-07-14 14:11 UTC, tomohitokanno requested changes
@ri-i-i-sa 
同一のタグ内でidとclass名の重複は避けてください。
`        <span class="total-text" id="total-text" hidden>合計金額 <span class="total-price"></span>`
上記のようなものです。

またコミットメッセージが良くないです。
`Reflecting code review.`
⇛なにをどうしたかを具体的に書いてください。どういうリファクタリングを行ったのかがこのコミットメッセージからは何も掴めません。

2023-07-14 14:11 UTC, tomohitokanno commented on assets/js/script.js
> +    formattedValue = formattedValue.substr(0, 11);
この行で敢えてformattedValueに代入をする必要を感じません。
formattedValueを介さずにinput.valueへ代入してはいけないのでしょうか？
formattedValueへ代入しないパターンでも動作確認してみてください。

2023-07-16 07:43 UTC, ri-i-i-sa commented
@tomohitokanno 

> 同一のタグ内でidとclass名の重複は避けてください。

について、どの様な使い分けをしたらいいか「同一タグ id class 命名」などで検索しているのですが該当記事が見つからず、命名に迷っています。
例えばどのような形がいいかのルールのアドバイスなど頂けたら嬉しいです。

お手数ですがご確認お願いいたします。

2023-07-16 08:30 UTC, tomohitokanno commented
@ri-i-i-sa 
使い分けを考えるのであれば
「id class 命名」、 「html id class 使い分け」のように検索してください。
idは具体的な命名
classは少し抽象的な命名をしてください。cssのコンポーネント名を接頭詞としてつけるのもいいかもしれません。

idを具体的に命名しないといけないのは、idには一意性が必要だからです。（例：佐藤太郎）
対して、classはそれらを包括した名前になります。（例：1年A組のみんな）

2023-07-16 09:23 UTC, ri-i-i-sa commented on assets/js/script.js
> +    formattedValue = formattedValue.substr(0, 11);
@tomohitokanno 
「formattedValueに代入」という意味合いがひょっとしたら私には理解出来ていないかもしれません。。
変数自体を再利用しているので、変数の宣言自体は可読性をあげるためには必要なのかという気もしておりますが、一旦
>formattedValueへ代入しないパターン

となるように修正を試みました。
意図した内容になっていますでしょうか？

2023-07-16 09:24 UTC, ri-i-i-sa commented
@tomohitokanno 
レビューでご指摘いただいた内容について修正対応が完了いたしました。
度々お手数ですがご確認お願いいたします。

2023-07-16 10:11 UTC, tomohitokanno requested changes

2023-07-16 10:11 UTC, tomohitokanno commented on index.html
> +                <p><input type="text" class="search-id" id="id-input" maxlength="4" placeholder="半角数字を入力" oninput="limitInputId(this)">
`class="search-id"`
は使用していないように見えます。使用する時にclassを定義しましょう。他の項目も同様です。

2023-07-16 10:21 UTC, tomohitokanno requested changes

2023-07-16 10:21 UTC, tomohitokanno commented on assets/js/script.js
> +    formattedValue = formattedValue.substr(0, 11);
@ri-i-i-sa 
いえ、意図した内容になっていません。まずは　https://github.com/ri-i-i-sa/member-management-system-project/pull/23/commits/cb54c08f73ec5c9b457f962f28e576009963dcbe をrevertしてください。

> 「formattedValueに代入」という意味合いがひょっとしたら私には理解出来ていないかもしれません。。
> 変数自体を再利用しているので、変数の宣言自体は可読性をあげるためには必要なのかという気もしておりますが、一旦
> 
> formattedValueへ代入しないパターン
> 
> となるように修正を試みました。
> 意図した内容になっていますでしょうか？

私の最初にした指摘では**この行で**とあるので、この行以外の箇所を大幅に変えないでください。
`let formattedValue = formatPhoneNumber(value); `
をsubstrした後にformattedValueに代入していますよね？

```
formattedValue = formattedValue.substr(0, 11);  ←これ
input.value = formattedValue; 
```

この代入が要らないと思っています。
なぜならsubstrした文字列をformattedValueに代入したとしても`input.value =` に値をセットして終わりだからです。

2023-07-16 13:27 UTC, ri-i-i-sa commented
@tomohitokanno 
度々すみません、
formattedValue = formattedValue.substr(0, 11); 
が必要かという件、ご指摘内容の意味合いは理解でき、修正したつもりなのですが電話番号の最後2桁が入力反映されなくなってしまいました。

自分でも見てみたのですが、原因が特定できず、そもそも間違っている可能性があるのでご確認いただけましたら幸いです。

お手数ですがご確認お願いいたします。

2023-07-17 06:38 UTC, ri-i-i-sa commented
@tomohitokanno 
追加でご指摘いただいた事項について修正が完了しております。
度々お手数ですが、ご確認お願いいたします。

2023-07-17 11:41 UTC, tomohitokanno requested changes

2023-07-17 11:41 UTC, tomohitokanno commented on assets/js/script.js
> +    input.setAttribute('maxlength', '13');
`input.setAttribute('maxlength', '13');`
はelseの分岐内でも使用されています。ということは分岐の外に書けば2行が1行で済みます。

2023-07-17 11:41 UTC, tomohitokanno commented on assets/js/script.js
>  function createHeaderDOM() {
`function createTableDataDOM`
に合わせてcreateTableHeaderDOMに変えましょう

2023-07-17 11:41 UTC, tomohitokanno commented on assets/js/script.js
> +function searchANDConditions (searchConditions, json){
これだけ関数名と引数の（）の間に半角空白があるので消しましょう。

2023-07-17 11:41 UTC, tomohitokanno commented on assets/js/script.js
> +function searchANDConditions (searchConditions, json){
` matchStatus = searchANDConditions (searchConditions, json[i]);`
関数の呼び出し元も同様に消してください

2023-07-17 11:41 UTC, tomohitokanno commented on assets/js/script.js
> +        matchStatus = searchANDConditions (searchConditions, json[i]);
matchStatusの変数のスコープ（var, let, const）を定義してください。

2023-07-17 11:41 UTC, tomohitokanno commented on index.html
> +            <input class="reset-btn text-medium" id="reset-button" type="submit" value="条件をクリア" >
classの命名を見ていくと
reset-btn　のように btn等の部品名が後ろに来るパターンと
button-history のように先頭に部品名を書いているパターンが混在しています。

idの命名は
reset-buttonやfurigana-inputのように、部品名が後ろに来るパターンになっています。

私の知見が足りないかもしれないので念のため確認ですが上記の法則は意図したものでしょうか？
意図したものでない場合、部品名を頭に書くような命名がいいかと思います。
理由としては、
```

input-id
input-name
input-furigana
matchThrough
matchTrue
matchFalse
```

のような命名にすると、inputやmatchと入力するとIDEの予測機能がその後ろの単語を含んで提示してくれるので、コーディングが楽になるためです。

2023-07-17 11:41 UTC, tomohitokanno commented on index.html
> +            <input class="reset-btn text-medium" id="reset-button" type="submit" value="条件をクリア" >
それとbuttonとbtnも混在しているので統一しましょう。

2023-07-18 11:56 UTC, ri-i-i-sa commented on assets/js/script.js
> +        matchStatus = searchANDConditions (searchConditions, json[i]);
@tomohitokanno 
修正する内容自体はわかったのですが、なぜここでスコープの定義が必要なのかがわからなくなってしまいました。。

2023-07-18 12:02 UTC, tomohitokanno commented on assets/js/script.js
> +        matchStatus = searchANDConditions (searchConditions, json[i]);
@ri-i-i-sa 
searchANDConditionsの方でも同一の変数名matchStatusが宣言されていますが、これはletで宣言されています。
この関数を実行した結果、matchStatusの値が返ってくるのですが、あくまで返ってくるのは値だけで、変数のスコープは引き継ぎません。
L:73では新たにmatchStatusという入れ物（変数）を用意しているので、再度スコープを定義する必要があります。

2023-07-18 12:38 UTC, ri-i-i-sa commented on index.html
> +            <input class="reset-btn text-medium" id="reset-button" type="submit" value="条件をクリア" >
@tomohitokanno 
仰る通り、接頭に部品名が来ることにおける利便性は理解出来ました。
現状のコーディングは厳密にBEMが採用出来ているとは言えないのですが、一応考え方としては参考にしています。
https://zenn.dev/nagan/articles/dac6fa662f4dab

「Block」「Element」「Modifier」の順で繋いでいく、というのが基本的な設計で、
>button-history のように先頭に部品名を書いているパターンが混在しています。

となっているのは単純に自分の考慮ミスです。

どちらに合わせても問題はないと思っているのですが、必要であれば統一します。

>それとbuttonとbtnも混在しているので統一しましょう。

に関しては取り急ぎ統一済です。

2023-07-18 12:44 UTC, tomohitokanno commented on index.html
> +            <input class="reset-btn text-medium" id="reset-button" type="submit" value="条件をクリア" >
@ri-i-i-sa 
> 仰る通り、接頭に部品名が来ることにおける利便性は理解出来ました。
> 現状のコーディングは厳密にBEMが採用出来ているとは言えないのですが、一応考え方としては参考にしています。

承知しました。
BEMによる命名規則による恩恵 > 私が提示した利点
と見えますので、規則として意識している、規則に従い正しく実施しているという状態であれば修正は不要です。

2023-07-18 14:01 UTC, ri-i-i-sa commented on assets/js/script.js
> +        matchStatus = searchANDConditions (searchConditions, json[i]);
@tomohitokanno 
度々説明していただいて恐縮なのですが、

> あくまで返ってくるのは値だけで、変数のスコープは引き継ぎません。
> L:73では新たにmatchStatusという入れ物（変数）を用意しているので、再度スコープを定義する必要があります

という点の意味合いが理解出来ずにいます。。
別のタイミングでも構いませんので口頭で確認させていただけたら嬉しいです。
取り急ぎ修正のみ反映しています。

2023-07-18 15:04 UTC, ri-i-i-sa commented
@tomohitokanno 
追加でご指摘いただいた内容につきまして、修正が完了しました。

お手数ですが、レビューをお願いいたします。

2023-07-18 23:55 UTC, tomohitokanno approved these changes
LGTM

2023-07-19 05:23 UTC, merged